launch:
  setup:
    sim:
      load_anymal_description:
        custom_parameters:
          depth_camera_resolution_width: 848
          depth_camera_resolution_height: 480
gui:
  operational_modes:
    50_dock:
      label: Dock
      requires_autonomy: true
docking_behavior_plugins:
  check_if_docked:
    topic: /pdb/pin_state
  dock:
    alternative_viewpoints:
      frame_id: point_cloud_odom
      poses:
        - orientation:
            w: 0.99144486137
            x: 0.0
            y: 0.0
            z: 0.13052619222
          position:
            x: 0.0
            y: 0.0
            z: 0.0
        - orientation:
            w: 0.99144486137
            x: 0.0
            y: 0.0
            z: 0.13052619222
          position:
            x: 0.0
            y: 0.0
            z: 0.0
        - orientation:
            w: 0.99144486137
            x: 0.0
            y: 0.0
            z: 0.13052619222
          position:
            x: 0.0
            y: 0.0
            z: 0.0
        - orientation:
            w: 0.99144486137
            x: 0.0
            y: 0.0
            z: 0.13052619222
          position:
            x: 0.0
            y: 0.0
            z: 0.0
        - orientation:
            w: 0.99144486137
            x: 0.0
            y: 0.0
            z: 0.13052619222
          position:
            x: 0.0
            y: 0.0
            z: 0.0
        - orientation:
            w: 0.99144486137
            x: 0.0
            y: 0.0
            z: 0.13052619222
          position:
            x: 0.0
            y: 0.0
            z: 0.0
    docking_station_alignment_pose:
      frame_id: docking_port
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -0.261
        y: 0.0
        z: 0.5
    docking_station_entry_pose:
      frame_id: docking_port
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -0.7
        y: 0.0
        z: 0.5
    docking_station_exit_pose:
      frame_id: docking_port
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -1.0
        y: 0.0
        z: 0.5
  undock:
    pose:
      frame_id: point_cloud_odom
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -0.5
        y: 0.0
        z: 0.0

docking_port_localization_ros:
  docking_port_depth_image_mux:
    lazy: true
  docking_port_intensity_image_mux:
    lazy: true
  docking_port_intensity_info_mux:
    lazy: true
  node:
    arc_pairs_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    bounding_box_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    camera_topics:
      front_lower:
        intensity_topic: /depth_camera_front_lower/infra1/image_rect_raw
        intensity_info_topic: /depth_camera_front_lower/infra1/camera_info
        depth_topic: /depth_camera_front_lower/depth/image_rect_raw
        rotation_angle: 180.0
      front_upper:
        intensity_topic: /depth_camera_front_upper/infra1/image_rect_raw
        intensity_info_topic: /depth_camera_front_upper/infra1/camera_info
        depth_topic: /depth_camera_front_upper/depth/image_rect_raw
        rotation_angle: 180.0
      left:
        intensity_topic: /depth_camera_left/infra1/image_rect_raw
        intensity_info_topic: /depth_camera_left/infra1/camera_info
        depth_topic: /depth_camera_left/depth/image_rect_raw
        rotation_angle: 0.0
      rear_lower:
        intensity_topic: /depth_camera_rear_lower/infra1/image_rect_raw
        intensity_info_topic: /depth_camera_rear_lower/infra1/camera_info
        depth_topic: /depth_camera_rear_lower/depth/image_rect_raw
        rotation_angle: 180.0
      rear_upper:
        intensity_topic: /depth_camera_rear_upper/infra1/image_rect_raw
        intensity_info_topic: /depth_camera_rear_upper/infra1/camera_info
        depth_topic: /depth_camera_rear_upper/depth/image_rect_raw
        rotation_angle: 180.0
      right:
        intensity_topic: /depth_camera_right/infra1/image_rect_raw
        intensity_info_topic: /depth_camera_right/infra1/camera_info
        depth_topic: /depth_camera_right/depth/image_rect_raw
        rotation_angle: 0.0
    camera_frame: camera
    debug_Drawings:
      arc_pairs_image:
        enable: true
        queue_size: 1
        topic: arc_pairs_image
      bounding_box_image:
        enable: true
        queue_size: 1
        topic: bounding_box_image
      depth_sampling_area_image:
        enable: true
        queue_size: 1
        topic: depth_sampling_area_image
      detected_arcs_image:
        enable: true
        queue_size: 1
        topic: detected_arcs_image
      edges_image:
        enable: true
        queue_size: 1
        topic: edges_image
      input_image:
        enable: true
        queue_size: 1
        topic: input_image
      lowest_ellipse_image:
        enable: true
        queue_size: 1
        topic: lowest_ellipse_image
      pre_processed_image:
        enable: true
        queue_size: 1
        topic: preprocessed_image
      quadruplet_neighbours_image:
        enable: true
        queue_size: 1
        topic: quadruplet_neighbours_image
      quadruplets_image:
        enable: true
        queue_size: 1
        topic: quadruplets_image
    depth_sampling_area_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    detected_arcs_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    detection:
      adaptive_threshold:
        max_value: 255
        threshold: 0
      arc_detection:
        min_length_arc: 10
        min_ratio_width_height: 0.05
      arc_pairing:
        max_distance: 30
      bounding_box:
        max_bounding_box_ratio: 2.9
        min_area_size: 500
        min_bounding_box_ratio: 1.3
      ellipse_extraction:
        min_ellipse_area: 400
      orientation_calculation:
        margin_around_sampling_area: 80
        min_area_of_sampling: 10
        number_of_sample_points: 200
        use_top_rect_for_sampling: false
      pre_processing:
        resize_factor: 1.0
      quadruplets:
        min_number_of_quadruplets: 1
      smoothing:
        kernel_size: 3
        sigma_x: 5
        sigma_y: 5
    edges_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    input_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    lowest_ellipse_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    node_configuration:
      april_tag_detection: true
      april_tag_master_id: 4
      custom_detection: true
      docking_port_frame_id: docking_port
      floor_frame_id: footprint
      max_timeout: 2.0
      number_of_images_to_analyze: 5
      pose:
        height_difference_threshold: 0.2
        max_pose_difference: 0.05
      publish_tag_image: true
      static_frame_id: point_cloud_odom
    preprocessed_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    publish_tf: true
    quadruplet_neighbours_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    quadruplets_image:
      compressed:
        format: jpeg
        jpeg_quality: 80
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    remove_duplicates: true
    servers:
      continuous_detection:
        service: toggle_continuous_detection
      get_docking_port:
        service: detect_docking_port
      get_docking_port_raw_pose:
        service: detect_docking_port_raw_pose
    standalone_tags:
      []
    subscribers:
      camera_info:
        queue_size: 1
        topic: /docking_port_localization_ros/intensity_info
      depth_image:
        queue_size: 10
        topic: /docking_port_localization_ros/depth_image
      image:
        queue_size: 1
        topic: /docking_port_localization_ros/intensity_image
    tag_blur: 0.0
    tag_bundles:
      - layout:
          - id: 4
            qw: 1
            qx: 0
            qy: 0
            qz: 0
            size: 0.05
            x: 0.0
            y: 0
            z: 0
          - id: 1
            qw: 1.0
            qx: 0.0
            qy: 0.0
            qz: 0.0
            size: 0.05
            x: 0.0
            y: -0.115
            z: 0.0
          - id: 2
            qw: -0.7071068
            qx: 0.0
            qy: 0.0
            qz: -0.7071068
            size: 0.05
            x: 0.115
            y: 0.0
            z: 0.0
          - id: 3
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 1.0
            size: 0.05
            x: 0.0
            y: 0.115
            z: 0.0
          - id: 0
            qw: -0.7071068
            qx: 0.0
            qy: 0.0
            qz: 0.7071068
            size: 0.05
            x: -0.115
            y: 0.0
            z: 0.0
        name: docking_port_local_frame
    tag_debug: 1.0
    tag_decimate: 1.0
    tag_family: tag36h11
    tag_refine_decode: 1.0
    tag_refine_edges: 1
    tag_threads: 2
slam:
  cameras_to_inspect:
    depth_camera_front_upper:
      camera_frame: "depth_camera_front_upper_depth_optical_frame"
      camera_topic: "/depth_camera_front_upper/infra1/image_rect_raw"
    depth_camera_front_lower:
      camera_frame: "depth_camera_front_lower_depth_optical_frame"
      camera_topic: "/depth_camera_front_lower/infra1/image_rect_raw"
    depth_camera_left:
      camera_frame: "depth_camera_left_depth_optical_frame"
      camera_topic: "/depth_camera_left/infra1/image_rect_raw"
    depth_camera_rear_upper:
      camera_frame: "depth_camera_rear_upper_depth_optical_frame"
      camera_topic: "/depth_camera_rear_upper/infra1/image_rect_raw"
    depth_camera_rear_lower:
      camera_frame: "depth_camera_rear_lower_depth_optical_frame"
      camera_topic: "/depth_camera_rear_lower/infra1/image_rect_raw"
    depth_camera_right:
      camera_frame: "depth_camera_right_depth_optical_frame"
      camera_topic: "/depth_camera_right/infra1/image_rect_raw"
  landmarks_for_localization:
    individual_labels:
      - "Docking Station"
    regex_labels:
      - "Localization April Tag.*"
  detection_frame_id_prefix: "detected_localization_apriltag_"
  publish_processed_tag_image: true
  num_images_to_analyze: 50
  camera_inspection_timeout: 5.0
  docking_station_z_offset_env: -0.5
  default_tag_config: &default_size
    size: 0.10
  tag_debug: 1.0
  tag_decimate: 1.0
  tag_family: tag36h11
  tag_refine_decode: 1.0
  tag_refine_edges: 1
  standalone_tags:
      [
        {
          id: 5,
          name: localization_tag_0,
          <<: *default_size
        },
        {
          id: 6,
          name: localization_tag_1,
          <<: *default_size
        },
        {
          id: 7,
          name: localization_tag_2,
          <<: *default_size
        },
      ]
  tag_bundles:
    - layout:
        - id: 4
          qw: 1
          qx: 0
          qy: 0
          qz: 0
          size: 0.05
          x: 0.0
          y: 0
          z: 0
        - id: 1
          qw: 1.0
          qx: 0.0
          qy: 0.0
          qz: 0.0
          size: 0.05
          x: 0.0
          y: -0.115
          z: 0.0
        - id: 2
          qw: -0.7071068
          qx: 0.0
          qy: 0.0
          qz: -0.7071068
          size: 0.05
          x: 0.115
          y: 0.0
          z: 0.0
        - id: 3
          qw: 0.0
          qx: 0.0
          qy: 0.0
          qz: 1.0
          size: 0.05
          x: 0.0
          y: 0.115
          z: 0.0
        - id: 0
          qw: -0.7071068
          qx: 0.0
          qy: 0.0
          qz: 0.7071068
          size: 0.05
          x: -0.115
          y: 0.0
          z: 0.0
      name: docking_port_local_frame
environment:
  object_types:
    docking_station:
      interactions:
        01_dock:
          label: Dock
          auto_control_required: true
          state_name:
            postfix: ""
            prefix: ""
          state_settings:
            []
          state_type: ""
        02_undock:
          label: Undock
          auto_control_required: true
          state_name:
            postfix: ""
            prefix: ""
          state_settings:
            []
          state_type: ""
      name: docking_station
      visualization:
        color:
          blue: 0.078125
          green: 0.4296875
          red: 0.078125
        mesh: package://environment_visualizer/meshes/navigation_goals/docking_station.dae
load_anymal_description:
  custom_parameters:
    docking_socket: true
operational_mode_manager:
  operational_modes:
    docking:
      type: TransitionalMode
      impl: operational_mode_manager::Docking
    undocking:
      type: TransitionalMode
      impl: operational_mode_manager::Undocking
    Dock:
      type: OperationalMode
      impl: operational_mode_manager::OperationalMode
  transitions:
    transition_15:
      source: undocking
      target: goToWalk
    transition_16:
      source: Walk
      target: docking
    transition_17:
      source: undocking
      target: goToStand
    transition_18:
      source: docking
      target: Dock
    transition_19:
      source: Dock
      target: undocking
robot_behavior_plugins:
  operate_reacting_on_low_battery:
    enable_docking_if_available: true
    automatic_reaction:
      enabled: true
      timeout: 180.0
rqt_task_execution:
  modes:
    list:
      50_dock:
        label: Dock
        icon_path: :/icons/dock_white.svg
        mode: 6
        requires_autonomy: true
rqt_environment_editor:
  plugins:
    docking_station:
      label: Docking Station
      name: docking_station_qt_plugin/DockingStationQtPlugin
rqt_supervisions:
  supervisions:
    docked:
      name: Docked
      topics:
        status: /behavior_engine/supervision/docked/status
        is_enabled: /behavior_engine/supervision/docked/is_enabled
        enable: /behavior_engine/supervision/docked/enable
rqt_state_machine_editor:
  behavior_plugins:
    system_behavior_plugins:
      namespace: system_behavior_plugins
      plugins:
        Dock: Dock
stack_launcher:
  nodes:
    docking_port_intensity_info_mux:
      roslaunch:
        args: /docking_port_localization_ros/intensity_info /depth_camera_front_lower/infra1/camera_info /depth_camera_front_upper/infra1/camera_info /depth_camera_left/infra1/camera_info /depth_camera_rear_lower/infra1/camera_info /depth_camera_rear_upper/infra1/camera_info /depth_camera_right/infra1/camera_info mux:=intensity_info
        name: docking_port_intensity_info_mux
        namespace: docking_port_localization_ros
        node_type: mux
        output: screen
        package: topic_tools
    docking_port_depth_image_mux:
      roslaunch:
        args: /docking_port_localization_ros/depth_image /depth_camera_front_lower/depth/image_rect_raw /depth_camera_front_upper/depth/image_rect_raw /depth_camera_left/depth/image_rect_raw /depth_camera_rear_lower/depth/image_rect_raw /depth_camera_rear_upper/depth/image_rect_raw /depth_camera_right/depth/image_rect_raw mux:=depth_image
        name: docking_port_depth_image_mux
        namespace: docking_port_localization_ros
        node_type: mux
        output: screen
        package: topic_tools
    docking_port_localization:
      roslaunch:
        name: node
        namespace: docking_port_localization_ros
        node_type: docking_port_localization_ros_node
        output: screen
        package: docking_port_localization_ros
    docking_port_intensity_image_mux:
      roslaunch:
        args: /docking_port_localization_ros/intensity_image /depth_camera_front_lower/infra1/image_rect_raw /depth_camera_front_upper/infra1/image_rect_raw /depth_camera_left/infra1/image_rect_raw /depth_camera_rear_lower/infra1/image_rect_raw /depth_camera_rear_upper/infra1/image_rect_raw /depth_camera_right/infra1/image_rect_raw mux:=intensity_image
        name: docking_port_intensity_image_mux
        namespace: docking_port_localization_ros
        node_type: mux
        output: screen
        package: topic_tools
  stacks:
    navigation:
      nodes:
        docking_port_intensity_info_mux:
          enabled: true
          name: docking_port_intensity_info_mux
        docking_port_depth_image_mux:
          enabled: true
          name: docking_port_depth_image_mux
        docking_port_localization:
          enabled: true
          name: docking_port_localization
        docking_port_intensity_image_mux:
          enabled: true
          name: docking_port_intensity_image_mux
