elevation_mapping:
  input_sources:
    hallucinated_input_front_lower:
      enabled: False
    hallucinated_input_front_upper:
      enabled: False
    hallucinated_input_left:
      enabled: False
    hallucinated_input_rear_lower:
      enabled: False
    hallucinated_input_rear_upper:
      enabled: False
    hallucinated_input_right:
      enabled: False