# See https://github.com/ethz-asl/libpointmatcher/blob/master/doc/Datafilters.md

readingDataPointsFilters: {}

referenceDataPointsFilters: {}

matcher:
  KDTreeMatcher:
    knn: 1
    maxDist: 1.0
    epsilon: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.9
  - SurfaceNormalOutlierFilter:
     maxAngle: 1.04

errorMinimizer:
  force4DOF: true

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.00001
      minDiffTransErr: 0.00001
      smoothLength: 4
  - CounterTransformationChecker:
      maxIterationCount: 50

inspector: NullInspector

logger: FileLogger