field_operator:
  walk_motion_states:
    blind_walk: blind_walk
motion_state_deduction:
  motion_transitioner:
    motion_states:
      _default_walk:
        direct_transit_state: blind_walk
    transitions:
      walk:
        motion:
          motion_controller: blind_walk
          operation_mode: blind_walk
          reference_type: twist
path_planning_and_following:
  strict_path_follower:
    motion_states:
      _default_walk: # same parameters as blind_walk
        dt_ref: 0.4
        acc_lim_theta: 0.45
        max_vel_theta: 0.9
        max_vel_x: 0.6
        max_vel_x_backwards: 0.6
        max_vel_y: 0.45
        min_vel_theta: 0.01
        min_vel_x: 0.02
        min_vel_y: 0.02
        weight_shortest_path: 4.0
