collision_filter:
  elevation_map_lidar_obstacle_pipeline:
    grid_map_source:
      filter_configurations:
        grid_map_height_mask:
          height_threshold: 0.275 # Controller is rated for 0.25 but we give margin of error for the obstacle avoidance.
motion_state_deduction:
  motion_transitioner:
    motion_states:
      _default_walk:
        direct_transit_state: perceptive_walk
    transitions:
      walk:
        motion:
          motion_controller: perceptive_walk
          operation_mode: perceptive_walk
          reference_type: twist
path_planning_and_following:
  elevation_map_lidar_obstacle_pipeline:
    grid_map_source:
      filter_configurations:
        grid_map_height_mask:
          height_threshold: 0.275 # Controller is rated for 0.25 but we give margin of error for the obstacle avoidance.
  strict_path_follower:
    motion_states:
      _default_walk: # same parameters as perceptive_walk
        dt_ref: 0.4
        acc_lim_theta: 0.35
        acc_lim_x: 0.35
        acc_lim_y: 0.35
        max_vel_theta: 0.9
        max_vel_x: 0.6
        max_vel_x_backwards: 0.6
        max_vel_y: 0.45
        min_vel_theta: 0.01
        min_vel_x: 0.02
        min_vel_y: 0.02
        weight_shortest_path: 4.0
