timeout_usec: 20000
self_see_links:
    - name: LF_thigh_fixed
      padding: 0.04
      filtering_method: projective
    - name: LH_thigh_fixed
      padding: 0.04
      filtering_method: projective
    - name: LF_KFE_drive
      padding: 0.08
    - name: LH_KFE_drive
      padding: 0.08
    - name: LF_shank_fixed
      padding: 0.1
    - name: LH_shank_fixed
      padding: 0.1
    - name: LF_FOOT
      padding: 0.04
    - name: LH_FOOT
      padding: 0.04
