timeout_usec: 20000
self_see_links:
    - name: RF_thigh_fixed
      padding: 0.04
      filtering_method: projective
    - name: RH_thigh_fixed
      padding: 0.04
      filtering_method: projective
    - name: RF_KFE_drive
      padding: 0.08
    - name: RH_KFE_drive
      padding: 0.08
    - name: RF_shank_fixed
      padding: 0.1
    - name: RH_shank_fixed
      padding: 0.1
    - name: RF_FOOT
      padding: 0.04
    - name: RH_FOOT
      padding: 0.04
